# Generated by Django 5.0.3 on 2024-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Movies', 'Movies'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Medical', 'Medical')], max_length=100, null=True),
        ),
    ]
