# Generated by Django 5.0.3 on 2024-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
